# AIM:

In this notebook we will see how to work with matrices using numpy

# Matrix multiplication Recap

In [1]:
from IPython.display import Image
from IPython.core.display import HTML
Image(url= "https://codeforwin.org/wp-content/uploads/2015/07/matrix-multiplication.png")

Thus, If we multiply a 2×3 matrix with a 3×1 matrix, the product matrix is 2×1. In general:

A($P\times Q) *  B(Q\times N) = O(P\times N$)

In [2]:
import numpy as np

In [3]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6,4],[7,8,10]])

In [4]:
print(x)
print(x.shape)

[[1 2]
 [3 4]]
(2, 2)


In [5]:
print(y)
print(y.shape)

[[ 5  6  4]
 [ 7  8 10]]
(2, 3)


In [6]:
c = np.matmul(x,y)

In [7]:
c

array([[19, 22, 24],
       [43, 50, 52]])

In [8]:
c.shape

(2, 3)

In [9]:
np.dot(x,y)

array([[19, 22, 24],
       [43, 50, 52]])

# NOTE:
matmul differs from dot in two important ways.

- Multiplication by scalars is not allowed.
- Stacks of matrices are broadcast together as if the matrices were elements.

In [10]:
np.matmul(5,x)

ValueError: Scalar operands are not allowed, use '*' instead

In [11]:
np.dot(5,x)

array([[ 5, 10],
       [15, 20]])

# Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

### Without Broadcasting

In [12]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) # 4x3
v = np.array([1, 0, 1]) # 1x3

In [13]:
vv = np.tile(v, (4, 1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [14]:
x+vv

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

### With Broadcasting 

In [15]:
x+v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])